### PR TITLE
Fix swagmaster420's yaml

### PR DESCRIPTION
**Pull request by ryansb**

### CODE REVIEW

**Comment by ryansb** [comment]
Closes #23

**Comment by msoucy** [comment]
Will still give undefined major information.

**Comment by liam-middlebrook** [comment]
:-1:

**Comment by ryansb** [comment]
It actually works, just leaving the major field blank in the template. 

I've updated it anyways with accurate major info.

**Comment by liam-middlebrook** [comment]
I feel that #27 is a better solution than this one.

**Pull request closed without merging**
